const std = @import("std");
const TValue = @import("core/value.zig").TValue;
const Proto = @import("vm/func.zig").Proto;
const VM = @import("vm/vm.zig").VM;
const opcodes = @import("compiler/opcodes.zig");
const Instruction = opcodes.Instruction;
const lexer = @import("compiler/lexer.zig");
const parser = @import("compiler/parser.zig");

pub fn main() !void {
    const stdout = std.io.getStdOut().writer();
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    // Test parser with simple Lua code
    const test_source = "return 1 + 2 + 3 * 4";

    try stdout.print("Testing parser with: {s}\n", .{test_source});
    try stdout.print("Tokens:\n", .{});
    lexer.dumpAllTokens(test_source);
    try stdout.print("\n", .{});

    // Test parser
    var lx = lexer.Lexer.init(test_source);
    var proto_builder = parser.ProtoBuilder.init(allocator);
    defer proto_builder.deinit();

    var p = parser.Parser.init(&lx, &proto_builder);
    try p.parseChunk();

    const proto = try proto_builder.toProto(allocator);
    defer allocator.free(proto.code);
    defer allocator.free(proto.k);

    try stdout.print("Generated bytecode:\n", .{});
    for (proto.code, 0..) |instr, i| {
        try stdout.print("{d}: {}\n", .{ i, instr });
    }

    try stdout.print("Constants:\n", .{});
    for (proto.k, 0..) |constant, i| {
        try stdout.print("K{d}: {}\n", .{ i, constant });
    }
    try stdout.print("\n", .{});

    // Test generated bytecode on VM
    var vm = VM.init();
    const result = try vm.execute(&proto);

    try stdout.print("Moonquakes speaks for the first time!\n", .{});
    try stdout.print("Compiling and executing Lua code: {s}\n", .{test_source});
    switch (result) {
        .none => try stdout.print("Result: nil\n", .{}),
        .single => |val| try stdout.print("Result: {}\n", .{val}),
        .multiple => |vals| {
            try stdout.print("Results: ", .{});
            for (vals, 0..) |val, i| {
                if (i > 0) try stdout.print(", ", .{});
                try stdout.print("{}", .{val});
            }
            try stdout.print("\n", .{});
        },
    }
}
